version: "2.1"
services:
  adsbtelegramnotify:
    image: adsbtelegramnotify:latest
    container_name: adsbtelegramnotify
    privileged: true
    environment:
      - TZ=Africa/Johannesburg
    volumes:
      - /opt/adsbtelegramnotify/config.php:/usr/src/myapp/includes/config.php:ro
      - /opt/adsbtelegramnotify/dump1090-fa/:/usr/src/myapp/readsb/:ro
    tty: true
    restart: unless-stopped
